### Commented Code – Pure Python
#### Example One

*Purpose:*
* A program to calculate prime numbers from 2 to n to be stored and retrieved in a dictionary.


*Structure of Python Code:*
* General program descriptionand Python reference (2.x or 3.x)
* Package imports (if needed for interpretation further down)
* Classes and Functions
* (MainClass) or Process Statements

**A sketch solution, a verbal description of what the programme should do helps in program design**

Step 0: Define an upper limit of prime number search

Step 1: Instantiate a nucleus of the dictionary with the first prime number ’p’ inscribed. pn= {2:’p’}

Step 2: Start a loop from 2+1 until upper limit of prime number search is reached. Set loop increment to 2 (only odd numbers can be prime numbers)

Step 3: We extend the dictionary with the actual loop variable

Step 4: We divide the value of the loop variable [3,…,n] by thepreviously detected prime numbers

Step 5: In step 4 one can reduce the number of divisions to all numbers smaller or equal sqrt(n)

Step 5: Once the first remainder-free division can be found, we delete the last entry (step 3) to the dictionary

Step 6: Print the contents of the dictionary = the prime numbers to the screen in ascending order, once the loop is exhausted

In [2]:
'''Calculate Prime Numbers from 2 to a maximum number
Store the prime numbers in a dictionary and
print the results in a stored order
Coding for Python 3.7
Example Programme 1
Version January 24
fir executive use in GIS-programming class '''

#imports

#functions

#user entries
nmax = 100

In [12]:
#calculate the prime numbers and fill dictionary

#start an initial prime number dictionary (one key/item only)
pn = {2:'p'}

#perform a loop from 3 to a maximum number nmax
for n in range(3, nmax, 2):
    #add new entry to prime number dictionary
    pn.update({n: 'p'})
    
    #divide by all previously stored prime numbers < sqrt(n)
    divs = [i for i in dict.keys(pn) if i <= n**0.5]
    
    for div in divs:
        if (n%div) == 0:
            #remove dictionary entry if division gives no reminder
            del pn[n]
            break
    
#create a stored output of the dictionary
for key in sorted(pn):
    print ("%i: %s" % (key, pn[key]))

2: p
3: p
5: p
7: p
11: p
13: p
17: p
19: p
23: p
29: p
31: p
37: p
41: p
43: p
47: p
53: p
59: p
61: p
67: p
71: p
73: p
79: p
83: p
89: p
97: p


**Lists**

In [15]:
import math
import random
classnmbs = range(1, 50)
print("List classnmbs: \n", list(classnmbs), "\n")

#List generation with just max number
a = range(5)
print("List a: \n", list(a), "\n")

#List generation with min and non-uncluded max number
b = range(3,8)
print("List b: \n", list(b), "\n")

#List generation with min, max, and step
c = range(3,8,2)
print("List c: \n", list(b), "\n")

List classnmbs: 
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49] 

List a: 
 [0, 1, 2, 3, 4] 

List b: 
 [3, 4, 5, 6, 7] 

List c: 
 [3, 4, 5, 6, 7] 



**List subsets and nested lists**

In [17]:
lst= [[1,2,3],[4,5,6],[7,8,9]]

#return first nested list
print(lst[1])

#return second value in first nested list
print(lst[1][2])

[4, 5, 6]
6


In [19]:
#sort list
lst= [2,1,3,4]
sortedList = sorted(lst)
print(sortedList)

[1, 2, 3, 4]


In [22]:
#add values to list
lst= [1,2,3,4]
lst.extend([5,6,7,8]) #adds new items to the existing lst:
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8]


How to change all occurrences of a specific list item (c.f. each 3 into 7)?
    by list comprehension:

In [26]:
lst= [1,3,2,5,2,3,3,6]
#if l is not equal to 3 then leave l, otherwise give 7 for each l in lst
lst= [l if l != 3 
      else 7 for l in lst]
print(list(lst))

[1, 7, 2, 5, 2, 7, 7, 6]


How to change all occurrences in a nested list (c.f. each 3 into 7)?
again by a nested list comprehension:

In [29]:
lst= [[1,2,3],[3,4,5],[3,3]]
lst= [[l if l!=3 
       else 7 for l in sublst] for sublst in lst]
print(list(lst))

[[1, 2, 7], [7, 4, 5], [7, 7]]


How to break up a list stored as a string into a list with individual items:

In [30]:
orig= '0 1 2 3 -1 4 7 6 5 -1 0 4 5 1 -1 '
orig2lst = orig.split()
print(orig2lst)

['0', '1', '2', '3', '-1', '4', '7', '6', '5', '-1', '0', '4', '5', '1', '-1']


How to subdivide the list into a nested list using the separator (in this case ”-1”).

In [31]:
orig2lst.pop()

'-1'

**Dictionaries {}:**

a key is mapped to an object

**Sets {}:**

similar to lists, but contain unique items (no duplication), are unordered, not indexed and consequently not slicable.

In [4]:
set1 = set(range(2,50))
print(set1)

{2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49}


How to remove repeated values in set1 and set2 from set1?

In [5]:
set2 = set(range(3, 40))
print(set2)

{3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39}


In [6]:
dif = list(set1 -set2)
print(list(dif))

[2, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


How to combine each record in set1 with each record in set2?

In [11]:
set3 = zip(set1, set2)
print(list(set3))

[(2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10), (10, 11), (11, 12), (12, 13), (13, 14), (14, 15), (15, 16), (16, 17), (17, 18), (18, 19), (19, 20), (20, 21), (21, 22), (22, 23), (23, 24), (24, 25), (25, 26), (26, 27), (27, 28), (28, 29), (29, 30), (30, 31), (31, 32), (32, 33), (33, 34), (34, 35), (35, 36), (36, 37), (37, 38), (38, 39)]


**Sequences**

is no data type on its own (!), it is just a class of data types supporting identical operations. 
Sequence types are:
* strings str() also including unicodestrings, 
* lists [], 
* tuples (), 
* xrange() as a sequence generator

In [13]:
# Boolean result
4 not in range(1,11,2)

True

**Functions *def:***

consist of an identifier (a function name), function parameters and an optional return value. Functions are a step towards more code legibility and code recycling.

In [14]:
def newFun(ixIn,strIn): # test input parameter
    if not (isinstance(ixIn, int) and isinstance(strIn, str)):
        return ""
    elif (ixIn < 0) or (ixIn >= len(strIn)):
        return ""
    # return one character at position ixIn
    else:
        return strIn[ixIn]

Example: Gradient from horizontal and vertical distance

In [4]:
dxy= [20.0, 17.0, 21.0, 25] # xydistance
dz= [2.0, 2.3, 1.0, 8.2] # z distance

# map() function is used to apply a function on all the elements of specified iterable and return map object
# A lambda function can take any number of arguments, but can only have one expression
# Syntax: lambda arguments : expression

# so here I can use grad function with two arguments X and Y
grad = map(lambda x, y: 100 * y/x, dxy, dz)

print(list(grad))

[10.0, 13.52941176470588, 4.761904761904762, 32.8]


In [5]:
for i,g in enumerate(grad):
    print("Gradient fuer %i in Prozent: %4.1f" % (i,g))

How to transform a simple list into a nested list (if -1 is a border btw these two nested lists)? (refers to line 31)

In [3]:
orig2lst = ['0','1','2','3','-1','4','7','6','5','-1']

def cutter(inlst, outlst, sep):
    buf= []
    while(inlst):
        e = inlst.pop(0)
        if e != sep:
            buf.append(int(e))
        else:
            outlst.append(buf)
            buf= []
    return outlst

cutter(orig2lst, [], '-1')

[[0, 1, 2, 3], [4, 7, 6, 5]]

In [6]:
origlst= [0, -1.9, 3, 99, 2, 4.4, 'strange', True]
def purify(inlst):
    ilst= []; 
    flst= []; 
    slst= [];
    for item in inlst:
        if isinstance(item, int):     # type check 1
            ilst.append(item)
        elif isinstance(item, float): # type check 2
            flst.append(item)
        elif isinstance(item, str):   # type check 3
            slst.append(item)
    return (ilst, flst, slst)

In [8]:
purify(origlst)

([0, 3, 99, 2, True], [-1.9, 4.4], ['strange'])

***Stumbling Blocks:***

Copies can be tricky:

In [11]:
#Objects
x = 4
y = x
y = 2
print(x, y)

4 2


In [13]:
#Lists
x = [1,2,3,4]
y = x
y.remove(3)
print(x, y)

[1, 2, 4] [1, 2, 4]


Consequence: If you have a list and intend to modify a copy only, the solution above fails! Perform a deep copy instead:

In [14]:
import copy
x = [1,2,3,4]
y = copy.deepcopy(x)
y.remove(3)
print(x, y)

[1, 2, 3, 4] [1, 2, 4]


In [15]:
#Slicing
x = [1,2,3,4]
y = x[:]
y.remove(3)
print(x, y)

[1, 2, 3, 4] [1, 2, 4]


Object identity and value identity may not be messed up:

In [22]:
a = 20
b = 20
if ( a is b ): # is tests for identical objects
    print("1: a and b have same identity")
else:
    print("1: a and b do not have same identity")
if ( id(a) == id(b) ): # id… tests for identical object id
    print("2: a and b have same identity")
else:
    print("2: a and b do not have same identity")
if ( a == b ): # == tests for identical value
    print("3: a and b have same value")
else:
    print("3: a and b do not have same value")

1: a and b have same identity
2: a and b have same identity
3: a and b have same value


In [23]:
c = copy.deepcopy(a)
if ( a is c ): # is tests for identical objects
    print("4: a and c have same identity")
else:
    print("4: a and cdo not have same identity")
if ( id(a) == id(c) ): # id… tests for identical object id
    print("5: a and c have same identity")
else:
    print ("5: a and c do not have same identity")
if ( a == c): # == tests for identical value
    print("6: a and c have same value")
else:
    print("6: a and c do not have same value")

4: a and c have same identity
5: a and c have same identity
6: a and c have same value


In [21]:
b = 30
if ( a is b ):
    print("7: a and b have same identity")
else:
    print("7: a and b do not have same identity")
if ( a is not b ):
    print("8: a and b do not have same identity")
else:
    print("8: a and b have same identity")

7: a and b do not have same identity
8: a and b do not have same identity


In a program we analyse a list and decide to eliminate n members using their known list indices.

In [25]:
origLst = [0,1,2,3,4,5] # our list
delIndices = [2,3] # indices earmarked to delete
# now start with the highest index instead:
for ix in reversed(delIndices):
    del origLst[ix]
print(origLst)

[0, 1, 4, 5]


Delete Members can also be performed using list comprehension

In [30]:
origLst = [0,1,2,3,4,5] # our list
delIndices = [2,3] # the indices of members to go

#now use list comprehension instead (only one line)
[m for ix, m in enumerate(origLst) if ix not in delIndices]

delValues = [origLst[ix] for ix in delIndices] 
for v in delValues:
    origLst.remove(v)
    
print(origLst)

[0, 1, 4, 5]


What would remove all members with a specific value from the list?

In [32]:
origLst= [5,4,3,4,2,3,6,8,2] 
# get rid of all members with the value 2
[o for o in origLst if o != 2]

[5, 4, 3, 4, 3, 6, 8]

How can we retrieve all indices of members of a given value (2)?

In [35]:
origLst= [4,3,2,1,5,4,3,2,2]
[ix for ix, m in enumerate(origLst) if m == 2]

[2, 7, 8]

How to retrieve indices of all identical members from two lists?

In [38]:
oLst0 = [1,2,3,4,5]
oLst1 = [5,4,3,2,1]
[ix for ix, (a, b) in enumerate(zip(oLst0, oLst1)) if a == b]

[2]

**Numpy**

Package for very concise and fast work with multi-dimensional array objects.

In [2]:
import numpy as np

A nested list is stored as a numpyarray, whilst the outer brackets enclose row elements, and the inner brackets enclose the column elements.

In [3]:
a = np.array( [[1,2,3,4], [5,6,7,8], [9,10,11,12]] )
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
# query the shape of the array
a.shape

(3, 4)

In [5]:
# change the shape from 3 x 4 into 4 x 3
a = np.reshape(a, (4,3))
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
# extract or modify individual elements by n-dimensional indexing
a[2,1]

8

In [7]:
a[2,1] = 18
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7 18  9]
 [10 11 12]]


In [8]:
# adding a new row b
b = np.array( [13, 14, 15] )
a = np.vstack((a,b))
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7 18  9]
 [10 11 12]
 [13 14 15]]


In [9]:
# a new column c
c = np.array( [16, 17, 18, 19, 20] )
a = np.hstack((a, np.reshape(c, (5,1))))
print(a)

[[ 1  2  3 16]
 [ 4  5  6 17]
 [ 7 18  9 18]
 [10 11 12 19]
 [13 14 15 20]]


complex data types can be defined and handled by a numpyarray:

In [10]:
mytype = np.dtype([('stat', np.unicode_, 20), ('code', np.uint16)])
print(mytype)

[('stat', '<U20'), ('code', '<u2')]


perform operations element by element without explicit looping:

In [11]:
d = np.array( [[-5, -4, -3], [-2, -1, 0], [1, 2, 3], [4, 5, 6], [7, 8, 9]] )
print(d)

[[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]


mask parts of an array using a booleanarray of equal size:

In [13]:
mask = np.array( 5 * [True, False, True] )
mask = np.reshape( mask, (5,3) )
print(mask)

[[ True False  True]
 [ True False  True]
 [ True False  True]
 [ True False  True]
 [ True False  True]]


In [20]:
print(a)
a[0,:]

[[ 1  2  3 16]
 [ 4  5  6 17]
 [ 7 18  9 18]
 [10 11 12 19]
 [13 14 15 20]]


array([ 1,  2,  3, 16])

In [17]:
a[:,2]

array([ 3,  6,  9, 12, 15])

In [19]:
#reverses row order
a[::-1]

array([[13, 14, 15, 20],
       [10, 11, 12, 19],
       [ 7, 18,  9, 18],
       [ 4,  5,  6, 17],
       [ 1,  2,  3, 16]])

In [21]:
#extract every second row
a[::2]

array([[ 1,  2,  3, 16],
       [ 7, 18,  9, 18],
       [13, 14, 15, 20]])

calculate various array statistics

In [23]:
#mean
np.mean(a)

11.0

In [26]:
#matrix algebra operations
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = [[1, 2], [3, 4], [5,6]]
c = np.dot(a, b)
c

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

* Calculate distance between coordinates

In [3]:
import math
a = [4,0] 
b = [6,6]

distance = math.sqrt((a[0] - b[0])**2 + (a[1] - b[1])**2)
print(distance)

6.324555320336759


* Find same values in two lists

In [6]:
a = [0, 1, 2, 3, 4]
b = [3, 4, 5]

c = []

for i in a:
    if i in b:
        c.append(i)
        
print(c)

[3, 4]
